# Generated by Django 5.2.1 on 2025-06-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Crop_Recommend',
            fields=[
                ('recommend_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nitrogen', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('Rainfall', models.FloatField()),
                ('pH', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('recommend_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nitrogen', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('Rainfall', models.FloatField()),
                ('pH', models.FloatField()),
            ],
        ),
    ]
