# Generated by Django 5.2.1 on 2025-06-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
