# Generated by Django 5.2.1 on 2025-07-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_recommend',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crop_recommend',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
