# Generated by Django 5.2.1 on 2025-07-01 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_crop_recommend_humidity_crop_recommend_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_recommend',
            name='Nitrogen',
        ),
        migrations.RemoveField(
            model_name='crop_recommend',
            name='Phosphorus',
        ),
        migrations.RemoveField(
            model_name='crop_recommend',
            name='Potassium',
        ),
        migrations.RemoveField(
            model_name='crop_recommend',
            name='Rainfall',
        ),
        migrations.RemoveField(
            model_name='crop_recommend',
            name='pH',
        ),
        migrations.AddField(
            model_name='crop_recommend',
            name='predicted_crop',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='crop_recommend',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crop_recommend',
            name='nitrogen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crop_recommend',
            name='phosphorus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crop_recommend',
            name='potassium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crop_recommend',
            name='rainfall',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crop_recommend',
            name='ph',
            field=models.FloatField(default=0.0),
        ),
    ]
