# Generated by Django 5.2.1 on 2025-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_crop_recommend_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='crop_images/')),
                ('description', models.TextField()),
                ('growth_duration', models.CharField(max_length=100)),
                ('best_season', models.CharField(max_length=100)),
                ('common_pests_diseases', models.TextField()),
                ('recommended_fertilizer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
