# Generated by Django 5.2.1 on 2025-07-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_crophistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropHistory',
        ),
    ]
