# Generated by Django 5.2.1 on 2025-07-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_crophistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdetail',
            name='growth_duration',
        ),
    ]
